Roshan gpg key
HorizenOfficial/keys pull request #73
Opened 2023-06-21 20:30 UTC by rbhrzlabs

2023-06-23 13:50 UTC, ysibirski submitted a review, later dismissed
LGTM

2023-06-23 20:21 UTC, ysibirski commented on index.html
> +    <a href="https://keys.openpgp.org/vks/v1/by-fingerprint/56020240F2BDDE011C10F1A08123F4B2EC40E890">0x8123F4B2EC40E890</a>
Link is pointing to the WRONG fingerprint

2023-06-23 20:21 UTC, ysibirski requested changes
Found 1 issue

2023-06-23 20:30 UTC, rbhrzlabs reviewed
fixed the index.html with correct URL

2023-06-23 20:54 UTC, ysibirski approved these changes
LGTM

2023-06-26 13:31 UTC, ysibirski commented on index.html
> +<<<<<<< HEAD
Merge conflict lines made into the commit. It needs to be resolved

2023-06-26 15:37 UTC, closed without merging